### ISSUE TITLE
工具或许失效？

### ISSUE THREAD

**Issue by Errl1l1l11** [FuckAntiAddiction/BiligameAddictionNotLimited#16]
昨天使用该工具可以正常登入，今天登入中自动登录认证能过，但是下一步就会卡住
![image](https://user-images.githubusercontent.com/93434424/139583949-4e6aa87e-0d0d-46e0-86ea-2547fecee05c.png)

**Comment by Errl1l1l11** [comment]
先进游戏再开工具的话，基建和每日任务互动无影响，但是关卡进出没法过

**Comment by Enaium** [comment]
不支持逍遥模拟器
