### ISSUE TITLE
按照步骤操作，认证系统服务失败，然后如果用127.0.0.1的服务器的话会连接失败

### ISSUE THREAD

**Issue by edge-bird** [FuckAntiAddiction/BiligameAddictionNotLimited#6]
![Screenshot_20210911-211151](https://user-images.githubusercontent.com/77676506/132949043-eb3c0744-e623-416a-b86f-b12a50397cea.png)
到了九点以后不会退出，但是如果进行操作就会提示无法连接然后就会退出来

**Comment by edge-bird** [comment]
然后这里是日志：
![Screenshot_20210911-212431](https://user-images.githubusercontent.com/77676506/132949370-c8f75caf-d2ca-479a-808a-9eaf07ec8b02.png)

**Comment by Enaium** [comment]
没有安装证书

**Comment by Enaium** [comment]
什么模拟器安卓什么版本

**Comment by edge-bird** [comment]
> 什么模拟器安卓什么版本

7.1.2，逍遥模拟器，内核是4.0.9

**Comment by edge-bird** [comment]
然后root模式开了，不知道符不符合使用条件

**Comment by edge-bird** [comment]
然后会显示“欢迎回来，不限制登录成功”的提示的，然后就认证系统服务失败了

**Comment by edge-bird** [comment]
然后还有就是一个问题，如果换地方登录同一个账号会出什么幺蛾子吗？

**Comment by Enaium** [comment]
点击启用按钮

**Comment by edge-bird** [comment]
> 点击启用按钮

现在关掉软件然后重新启动，进方舟还是认证系统服务失败

**Comment by edge-bird** [comment]
啊似乎成功了，先打开方舟然后再打开软件，然后没有启用，好像就可以了

**Comment by Enaium** [comment]
> 
> 
> 然后还有就是一个问题，如果换地方登录同一个账号会出什么幺蛾子吗？

会被挤掉 之后也会失效 就要重新等到周末20:00 重新登录

**Comment by edge-bird** [comment]
> > 然后还有就是一个问题，如果换地方登录同一个账号会出什么幺蛾子吗？
> 
> 会被挤掉 之后也会失效 就要重新等到周末20:00 重新登录

好的，还好晚自修在机房……

**Comment by edge-bird** [comment]
证书的话不是启动后保存吗，怎么安装

**Comment by edge-bird** [comment]
建议作者出一个能够笼统所有游戏的教程
