### ISSUE TITLE
碧蓝航线解除登录限制无效，但其他游戏有效

### ISSUE THREAD

**Issue by Kripaspaka** [FuckAntiAddiction/BiligameAddictionNotLimited#7]
去下了两个B服的其他游戏试了试，功能一切正常
但碧蓝航线登录时用户名依然是原名，且在有自动登录的情况下重启游戏依然存在限制
不过充值限制和时长限制都成功解除了
登录时日志依然提示解除登录限制成功

**Comment by Enaium** [comment]
新版登录的获取用户信息换了个地址

**Comment by Enaium** [comment]
解决了

**Comment by Hantaisang** [comment]
为什么我按照要求去做，登录的时候显示原名，然后进不去，显示系统错误，软件日志里也没有拦截成功的提示？

**Comment by Skouthys** [comment]
登录显示原名无法进入游戏，退出重进后显示账号是什么问题
